name: webdav_x
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^10.3.7
  http: ^1.6.0
  intl: ^0.20.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  webdav_client: ^1.2.2
  window_manager: ^0.5.1
  google_fonts: ^6.3.2
  chinese_font_library: ^1.2.0
  path_provider: ^2.1.5
  flutter_smart_dialog: ^4.9.8+9
  screen_retriever: ^0.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  animations: ^2.1.1
  encrypt: ^5.0.3
  url_launcher: ^6.3.2
  pointycastle: ^3.9.1
  open_file_manager: ^2.0.1
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  names_launcher: ^0.0.2 

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icon/

names_launcher:
  name:
    default: "WebDav X"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    windows:
      enable: false